# Generated by Django 3.2.3 on 2021-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cont', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('publications', models.BooleanField(default=True, verbose_name='Опубликовоно')),
                ('company', models.ManyToManyField(blank=True, to='cont.Company', verbose_name='Компания')),
                ('fixed', models.ManyToManyField(blank=True, to='user.User', verbose_name='Закреплено')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date_creation'],
            },
        ),
    ]
