# Generated by Django 3.2 on 2021-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Документ'),
        ),
    ]
