# Generated by Django 3.2 on 2021-05-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_alter_document_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doc.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doc.user', verbose_name='Имя'),
        ),
    ]
