# Generated by Django 3.2.3 on 2021-06-02 13:22

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('cont', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOutgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Исходящий')),
                ('company_02', models.CharField(max_length=255, verbose_name='Компания (Быстрая запись)')),
                ('document', models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Документ')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('publications', models.BooleanField(default=True, verbose_name='Опубликовоно')),
                ('CategoryOutgoing', models.ManyToManyField(blank=True, to='outgoing.CategoryOutgoing', verbose_name='Каиегория')),
                ('company', models.ManyToManyField(blank=True, to='cont.Company', verbose_name='Компания')),
                ('fixed', models.ManyToManyField(blank=True, to='user.User', verbose_name='Закреплено')),
            ],
            options={
                'verbose_name': 'Исходящий',
                'verbose_name_plural': 'Исходящие',
                'ordering': ['-date_creation'],
            },
        ),
    ]
