# Generated by Django 3.2.3 on 2021-06-01 10:12

from django.db import migrations, models
import django_ckeditor_5.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ООО "НПО "АГАТ"', max_length=500, verbose_name='Название')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=50, unique=True, verbose_name='КПП')),
                ('address', models.TextField(blank=True, help_text='196247, Российская Федерация, город Санкт-Петербург, площадь Конституции, дом 2', max_length=500, verbose_name='Адрес')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, upload_to='logo/%Y/%m/%d/', verbose_name='Логотип')),
                ('card', models.FileField(blank=True, upload_to='card/%Y/%m/%d/', verbose_name='Карточка')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Веб-сайта')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('publications', models.BooleanField(default=True, verbose_name='Опубликовоно')),
                ('fixed', models.ManyToManyField(blank=True, to='user.User', verbose_name='Закреплено')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('surname', models.CharField(max_length=500, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=500, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Мобильный телефон')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Веб-сайта')),
                ('date_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('publications', models.BooleanField(default=True, verbose_name='Опубликовоно')),
                ('company', models.ManyToManyField(blank=True, to='cont.Company', verbose_name='Компания')),
                ('position', models.ManyToManyField(blank=True, to='user.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['date_creation'],
            },
        ),
    ]
